server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true
    show-sql: false

  application:
    name: "flightbooking"
  mvc:
    static-path-pattern: /static/**
    hidden-method:
      filter:
        enabled: true
  freemarker:
    expose-request-attributes: true
    settings:
      boolean_format: c
    cache: false
  datasource:
    url: jdbc:h2:./db/booking;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: classpath:/db/changelog/master.yml
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: error
    org:
      hibernate:
        type: error
        stat: error
      springframework:
        security: debug
        web: debug
        messaging: debug
      attractor:
        flightbooking: debug
    web: info
    sql: error
  logback:
    file: logs/application.log